### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'click')

### ISSUE THREAD

**Issue by xspeed1989** [adamlui/autoclear-chatgpt-history#20]
Uncaught TypeError: Cannot read properties of null (reading 'click')
    at Object.cb (自动清除 ChatGPT 历史记录 🕶️.user.js:422:53)
    at Boolean.Command (injected-web.js:1:14830)
    at Object.onHandle (injected-web.js:1:3056)
    at injected-web.js:1:3796

**Comment by adamlui** [comment]
@xspeed1989 what's your browser and version, and what other scripts are you running?

**Comment by xspeed1989** [comment]
> @xspeed1989 what's your browser and version, and what other scripts are you running?

chrome version: 119.0.6045.200
violentmonkey version:2.16.0

**Comment by adamlui** [comment]
@xspeed1989 the latest chatgpt.com UI update made it so the menu button is no longer clickable, but if you update to latest version 2024.5.17.6 @ https://greasyfork.autoclearchatgpt.com it will use a back-end API method instead, but the downside is your chat history list will still be visible until browser refresh, but the messages are actually deleted already

**Comment by adamlui** [comment]
@xspeed1989 in the future I can add some way to clear the browser-side visual history though, or if OpenAI ever makes the menu button `.click()`able again then when script updates to newest chatgpt.js around that time, it will auto-use DOM method instead
